name: Build the App
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Installation Node js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Check version
      run: node -v
    - name: Install dependency
      run: npm install
    - name: Test Cases test
      run: npm run test
    - name: Update status
      run: echo "Testing Completed"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Installation Node js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Check version
      run: node -v
    - name: Install dependency
      run: npm install
    - name: deploy
      run: echo "Deployed"