name: Build the App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Installation Node js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Check version
      run: node -v
    - name: Install dependency
      run: npm install
    - name: Update status
      run: echo "Deployed Done"